using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace KazakhNinja.EditorTools
{
    /// <summary>
    /// Hooks the Blender food models into the game. The models and their baked textures are generated by
    /// ArtSource/Foods/scripts (see its foods.py) into Models/Foods:
    ///   {id}.fbx             one closed mesh, one material, centred, sized in game units
    ///   {id}_BaseColor.png   albedo, smoothness in alpha
    ///   {id}_Normal.png      tangent-space normal map
    ///   {id}_Inside.png      cut surface, projected planar by the slicer
    /// "Apply Food Models" points every FoodDefinition with a model at it, textures its existing
    /// materials (keeping their emission / metallic tuning) and re-bakes the collection icons.
    /// </summary>
    public sealed class FoodArtImporter : AssetPostprocessor
    {
        const string ModelFolder = "Assets/_Game/Models/Foods";
        const string TextureFolder = ModelFolder + "/Textures";
        const string FoodFolder = "Assets/_Game/Data/Foods";

        void OnPreprocessModel()
        {
            if (!assetPath.StartsWith(ModelFolder + "/")) return;
            var importer = (ModelImporter)assetImporter;
            importer.isReadable = true; // sliced at runtime
            importer.materialImportMode = ModelImporterMaterialImportMode.None;
            importer.importAnimation = false;
            importer.animationType = ModelImporterAnimationType.None;
            importer.importCameras = false;
            importer.importLights = false;
            importer.importBlendShapes = false;
            importer.importVisibility = false;
            importer.meshCompression = ModelImporterMeshCompression.Off;
            importer.importNormals = ModelImporterNormals.Import;
            importer.importTangents = ModelImporterTangents.CalculateMikk; // matches the Blender bake
            importer.bakeAxisConversion = true;
        }

        void OnPreprocessTexture()
        {
            if (!assetPath.StartsWith(TextureFolder + "/")) return;
            var importer = (TextureImporter)assetImporter;
            string name = Path.GetFileNameWithoutExtension(assetPath);
            importer.mipmapEnabled = true;
            importer.alphaIsTransparency = false;
            if (name.EndsWith("_Normal"))
            {
                importer.textureType = TextureImporterType.NormalMap;
                importer.maxTextureSize = 1024;
                return;
            }
            importer.textureType = TextureImporterType.Default;
            importer.sRGBTexture = true;
            importer.alphaSource = name.EndsWith("_BaseColor") ? TextureImporterAlphaSource.FromInput : TextureImporterAlphaSource.None;
            importer.maxTextureSize = name.EndsWith("_Inside") ? 512 : 1024;
        }

        /// <summary>Metallic override per food; everything else is dielectric.</summary>
        static float MetallicOf(string id) => id switch
        {
            "toy" => 1f,
            "golden_aport" => 0.45f,
            _ => 0f,
        };

        [MenuItem("Kazakh Ninja/Apply Food Models", priority = 30)]
        public static void Apply()
        {
            int applied = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:FoodDefinition", new[] { FoodFolder }))
            {
                var food = AssetDatabase.LoadAssetAtPath<FoodDefinition>(AssetDatabase.GUIDToAssetPath(guid));
                if (food == null) continue;
                Mesh mesh = AssetDatabase.LoadAllAssetsAtPath($"{ModelFolder}/{food.id}.fbx").OfType<Mesh>().FirstOrDefault();
                var baseMap = AssetDatabase.LoadAssetAtPath<Texture2D>($"{TextureFolder}/{food.id}_BaseColor.png");
                if (mesh == null || baseMap == null || food.skinMaterials == null || food.skinMaterials.Length == 0) continue;

                Material skin = food.skinMaterials[0];
                var normalMap = AssetDatabase.LoadAssetAtPath<Texture2D>($"{TextureFolder}/{food.id}_Normal.png");
                SetupSkin(skin, baseMap, normalMap, MetallicOf(food.id));

                var insideMap = AssetDatabase.LoadAssetAtPath<Texture2D>($"{TextureFolder}/{food.id}_Inside.png");
                if (insideMap != null && food.insideMaterial != null)
                {
                    food.insideMaterial.SetTexture("_BaseMap", insideMap);
                    food.insideMaterial.SetColor("_BaseColor", Color.white);
                    EditorUtility.SetDirty(food.insideMaterial);
                }

                food.mesh = mesh;
                food.skinMaterials = new[] { skin };
                food.scale = Vector3.one;
                EditorUtility.SetDirty(food);
                applied++;
            }
            AssetDatabase.SaveAssets();
            Debug.Log($"Kazakh Ninja: applied Blender models to {applied} foods.");
            IconBaker.Bake(true);
        }

        static void SetupSkin(Material material, Texture2D baseMap, Texture2D normalMap, float metallic)
        {
            material.SetTexture("_BaseMap", baseMap);
            material.SetColor("_BaseColor", Color.white);
            // Smoothness comes from the albedo alpha; _Smoothness scales it.
            material.SetFloat("_SmoothnessTextureChannel", 1f);
            material.EnableKeyword("_SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A");
            material.SetFloat("_Smoothness", 1f);
            material.SetFloat("_Metallic", metallic);
            if (normalMap != null)
            {
                material.SetTexture("_BumpMap", normalMap);
                material.SetFloat("_BumpScale", 1f);
                material.EnableKeyword("_NORMALMAP");
            }
            EditorUtility.SetDirty(material);
        }
    }
}
